In [1]:
using Images, Colors, DecisionTree, DataFrames

In [2]:
imageSize = 400

400

In [3]:
path = "./images"

"./images"

In [4]:
function read_data(typeData, labelsInfo, imageSize, path)
    x = zeros(size(labelsInfo, 1), imageSize)
    for (index, idImage) in enumerate(labelsInfo[:ID])
        nameFile = "$(path)/$(typeData)Resized/$(idImage).Bmp"
        img = load(nameFile)
        temp = convert(Image{Gray}, img)
        x[index, :] = reshape(temp, 1, imageSize)
    end
    return x
end     

read_data (generic function with 1 method)

In [5]:
labelsInfoTrain = readtable("$(path)/trainLabels.csv")

6283×2 DataFrames.DataFrame
│ Row  │ ID   │ Class │
├──────┼──────┼───────┤
│ 1    │ 1    │ "n"   │
│ 2    │ 2    │ "8"   │
│ 3    │ 3    │ "T"   │
│ 4    │ 4    │ "I"   │
│ 5    │ 5    │ "R"   │
│ 6    │ 6    │ "W"   │
│ 7    │ 7    │ "L"   │
│ 8    │ 8    │ "l"   │
│ 9    │ 9    │ "K"   │
│ 10   │ 10   │ "G"   │
│ 11   │ 11   │ "A"   │
⋮
│ 6272 │ 6272 │ "t"   │
│ 6273 │ 6273 │ "S"   │
│ 6274 │ 6274 │ "e"   │
│ 6275 │ 6275 │ "l"   │
│ 6276 │ 6276 │ "O"   │
│ 6277 │ 6277 │ "R"   │
│ 6278 │ 6278 │ "L"   │
│ 6279 │ 6279 │ "N"   │
│ 6280 │ 6280 │ "I"   │
│ 6281 │ 6281 │ "P"   │
│ 6282 │ 6282 │ "N"   │
│ 6283 │ 6283 │ "R"   │

In [6]:
xTrain = read_data("train", labelsInfoTrain, imageSize, path)

6283×400 Array{Float64,2}:
 0.243137   0.25098    0.34902    …  0.278431   0.270588   0.278431 
 0.462745   0.462745   0.462745      0.458824   0.454902   0.454902 
 0.317647   0.384314   0.384314      0.372549   0.341176   0.305882 
 0.301961   0.364706   0.560784      0.564706   0.572549   0.54902  
 0.0862745  0.0862745  0.0823529     0.0705882  0.0745098  0.0745098
 0.419608   0.419608   0.419608   …  0.407843   0.407843   0.415686 
 0.286275   0.278431   0.278431      0.278431   0.278431   0.282353 
 0.243137   0.203922   0.215686      0.243137   0.254902   0.254902 
 0.247059   0.235294   0.235294      0.235294   0.239216   0.235294 
 0.784314   0.784314   0.772549      0.964706   0.952941   0.945098 
 0.364706   0.360784   0.356863   …  0.45098    0.439216   0.45098  
 0.266667   0.254902   0.258824      0.270588   0.270588   0.262745 
 0.235294   0.219608   0.219608      0.313725   0.196078   0.117647 
 ⋮                                ⋱                                 
 0.6156

In [7]:
labelsInfoTest = readtable("$(path)/sampleSubmission.csv")

6220×2 DataFrames.DataFrame
│ Row  │ ID    │ Class │
├──────┼───────┼───────┤
│ 1    │ 6284  │ "A"   │
│ 2    │ 6285  │ "A"   │
│ 3    │ 6286  │ "A"   │
│ 4    │ 6287  │ "A"   │
│ 5    │ 6288  │ "A"   │
│ 6    │ 6289  │ "A"   │
│ 7    │ 6290  │ "A"   │
│ 8    │ 6291  │ "A"   │
│ 9    │ 6292  │ "A"   │
│ 10   │ 6293  │ "A"   │
│ 11   │ 6294  │ "A"   │
⋮
│ 6209 │ 12492 │ "A"   │
│ 6210 │ 12493 │ "A"   │
│ 6211 │ 12494 │ "A"   │
│ 6212 │ 12495 │ "A"   │
│ 6213 │ 12496 │ "A"   │
│ 6214 │ 12497 │ "A"   │
│ 6215 │ 12498 │ "A"   │
│ 6216 │ 12499 │ "A"   │
│ 6217 │ 12500 │ "A"   │
│ 6218 │ 12501 │ "A"   │
│ 6219 │ 12502 │ "A"   │
│ 6220 │ 12503 │ "A"   │

In [8]:
xTest = read_data("test", labelsInfoTest, imageSize, path)

6220×400 Array{Float64,2}:
 0.45098   0.447059  0.443137  0.443137  …  0.486275  0.482353  0.470588
 0.282353  0.286275  0.309804  0.301961     0.431373  0.282353  0.294118
 0.113725  0.152941  0.156863  0.156863     0.145098  0.145098  0.101961
 0.592157  0.545098  0.564706  0.529412     0.556863  0.588235  0.592157
 0.501961  0.52549   0.552941  0.564706     0.572549  0.588235  0.541176
 0.552941  0.54902   0.54902   0.552941  …  0.533333  0.509804  0.501961
 0.141176  0.180392  0.192157  0.176471     0.14902   0.164706  0.156863
 0.862745  0.866667  0.843137  0.866667     0.862745  0.905882  0.882353
 0.705882  0.694118  0.686275  0.698039     0.643137  0.670588  0.701961
 0.866667  0.866667  0.866667  0.866667     0.878431  0.886275  0.905882
 0.231373  0.2       0.203922  0.235294  …  0.215686  0.227451  0.239216
 0.737255  0.74902   0.776471  0.780392     0.776471  0.780392  0.780392
 0.47451   0.47451   0.494118  0.490196     0.454902  0.478431  0.478431
 ⋮                      

In [9]:
yTrain = map(x -> x[1], labelsInfoTrain[:Class])

6283-element DataArrays.DataArray{Any,1}:
 'n'
 '8'
 'T'
 'I'
 'R'
 'W'
 'L'
 'l'
 'K'
 'G'
 'A'
 'A'
 'C'
 ⋮  
 't'
 'S'
 'e'
 'l'
 'O'
 'R'
 'L'
 'N'
 'I'
 'P'
 'N'
 'R'

In [18]:
yTrain = map(Int, yTrain)
yTrain = convert(Array{Int64,1},yTrain)

6283-element Array{Int64,1}:
 110
  56
  84
  73
  82
  87
  76
 108
  75
  71
  65
  65
  67
   ⋮
 116
  83
 101
 108
  79
  82
  76
  78
  73
  80
  78
  82

In [19]:
model = build_forest(yTrain, xTrain, 20, 50, 1.0)

Ensemble of Decision Trees
Trees:      50
Avg Leaves: 2193.5
Avg Depth:  18.96

In [20]:
predTest = apply_forest(model, xTest)

6220-element Array{Any,1}:
  72
  69
  55
  79
  69
  69
  79
  77
 101
  72
  78
 111
  65
   ⋮
  65
  65
  65
  67
  69
  84
  69
  79
  69
  82
  78
  77

In [24]:
labelsInfoTest[:Class] = map(Char, predTest)

6220-element Array{Char,1}:
 'H'
 'E'
 '7'
 'O'
 'E'
 'E'
 'O'
 'M'
 'e'
 'H'
 'N'
 'o'
 'A'
 ⋮  
 'A'
 'A'
 'A'
 'C'
 'E'
 'T'
 'E'
 'O'
 'E'
 'R'
 'N'
 'M'

In [25]:
writetable("$(path)/juliaSubmission.csv", labelsInfoTest, separator=',', header=true)

In [26]:
accuracy = nfoldCV_forest(yTrain, xTrain, 20, 50, 4, 1.0);


Fold 1
Classes:  

62×62 Array{Int64,2}:
 2  0  0  0  0  0  0  0  0  0   1  0  …  1  0  0  0  0  0  0  0  0  0  0  0
 0  7  0  0  0  0  0  0  0  0   2  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  7  0  0  0  0  0  0  0   1  0     0  0  0  0  0  2  0  0  0  0  0  0
 0  0  0  4  0  0  0  0  0  0   1  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  1  0  0  0  0  0   3  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0   2  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0   1  0     0  0  0  0  1  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  5  0  0   0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0   0  0     1  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0   2  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  96  1  …  0  0  0  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  0  0  0  0   2  2     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0   0  0     0  0  0  0  0  1  0  0  0

Any[48,49,50,51,52,53,54,55,56,57,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122]
Matrix:   
Accuracy: 0.43248407643312103
Kappa:    0.4077352978534231


62×62 Array{Int64,2}:
 3  0  0  0  0  0  0  0  0  0   4  0  …  1  0  0   0  0  0  0  0  0  0  0  0
 0  4  0  0  0  0  0  0  0  0   0  0     0  0  0   0  0  0  0  0  0  0  0  0
 0  0  3  0  0  0  0  0  0  0   1  0     0  0  0   0  0  0  0  0  0  0  0  0
 0  0  0  2  0  0  0  0  0  0   0  1     0  0  0   0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0   4  0     0  0  0   0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  0  0  0  0   2  0  …  0  0  0   0  1  0  0  0  0  0  0  0
 0  0  0  0  0  0  3  0  0  0   4  0     0  0  0   0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  3  0  0   1  0     0  0  0   0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0   0  1     0  0  0   0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  2   0  0     0  0  0   0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  1  99  1  …  0  0  0   1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0   6  3     0  0  0   1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0   0  0     1  0  0   0  


Fold 2
Classes:  Any[48,49,50,51,52,53,54,55,56,57,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122]
Matrix:   
Accuracy: 0.4394904458598726
Kappa:    0.4146687832812865

Fold 3

62×62 Array{Int64,2}:
 2  0  0  0  0  0  1  0  0  0   4  0  …  0  0   0  0   0  0  0  0  0  0  0
 0  3  0  0  0  0  0  0  0  0   0  0     0  0   0  0   0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0   2  0     0  0   0  0   0  0  0  0  0  0  0
 0  0  0  2  0  0  0  0  0  0   0  0     0  0   0  0   0  0  0  0  0  0  0
 0  0  0  0  1  0  0  0  0  0   6  0     0  0   0  0   0  0  0  0  0  0  0
 0  0  0  0  0  0  1  0  0  0   2  1  …  0  0   0  0   0  0  0  0  0  0  0
 0  0  0  0  0  0  3  0  0  0   0  1     0  0   0  0   0  0  0  0  0  0  0
 0  0  1  0  0  0  0  2  0  0   0  0     0  0   0  0   0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  0   0  0     0  0   0  0   0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  2   0  0     0  0   0  0   0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  96  0  …  0  0   0  0   0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0   5  4     0  0   0  0   0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0   3  0     0  0   1  0   0  0  0  0  0  1  0
 ⋮ 


Classes:  Any[48,49,50,51,52,53,54,55,56,57,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122]
Matrix:   
Accuracy: 0.4356687898089172
Kappa:    0.41068587805906187

Fold 4
Classes:  

62×62 Array{Int64,2}:
 4  0  0  0  0  0  0  0  0  0   0  0  …  2  0  0   0  0  0  0  0  0  0  0  0
 0  3  0  0  1  0  0  0  0  0   0  0     0  0  0   0  0  0  0  0  0  0  0  0
 0  0  3  0  0  0  0  0  0  0   5  0     0  0  0   0  0  1  0  0  0  0  0  0
 0  0  0  2  0  0  0  0  0  0   2  0     0  0  0   0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0   4  0     0  0  0   0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  0  0  0  0   0  0  …  0  0  0   0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  3  0  0  0   0  0     0  0  0   0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  3  0  1   0  0     0  0  0   0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  1  0  0  0   0  0     0  0  0   0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0   0  0     0  0  0   1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  88  0  …  2  0  0   0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0   5  1     0  0  0   1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0   1  0     0  0  0   1  

Any[48,49,50,51,52,53,54,55,56,57,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122]
Matrix:   
Accuracy: 0.41337579617834397
Kappa:    0.3873621112465025

Mean Accuracy: 0.4302547770700637


In [34]:
println("4 fold accuracy: $(mean(accuracy))")

4 fold accuracy: 0.4302547770700637


In [29]:
mean(accuracy)

0.4302547770700637